# Generated by Django 5.2.11 on 2026-02-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0002_constraints_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="despesasecretaria",
            new_name="financas_de_ano_341487_idx",
            old_name="financas_de_ano_89df8a_idx",
        ),
    ]
