# Generated by Django 5.2.11 on 2026-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_rename_financas_de_ano_89df8a_idx_financas_de_ano_341487_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('ano', models.IntegerField(db_index=True)),
                ('autoria', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('origem_recurso', models.CharField(blank=True, max_length=120)),
                ('objeto', models.TextField(blank=True)),
                ('funcao_governo', models.CharField(blank=True, max_length=255)),
                ('beneficiario', models.CharField(blank=True, max_length=255)),
                ('unidade', models.CharField(blank=True, max_length=255)),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_empenhado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_liquidado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('data_emenda', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-valor_previsto'],
                'indexes': [models.Index(fields=['ano', 'autoria'], name='financas_em_ano_55ac8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(db_index=True)),
                ('orgao_cod', models.CharField(blank=True, max_length=20)),
                ('unidade', models.CharField(max_length=255)),
                ('acao', models.CharField(blank=True, max_length=255)),
                ('funcao', models.CharField(blank=True, max_length=120)),
                ('subfuncao', models.CharField(blank=True, max_length=120)),
                ('natureza_despesa', models.CharField(blank=True, max_length=30)),
                ('elemento_despesa', models.CharField(blank=True, max_length=255)),
                ('fonte_recurso', models.CharField(blank=True, max_length=255)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_atualizado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_disponivel', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'ordering': ['-valor_inicial'],
                'indexes': [models.Index(fields=['ano', 'unidade'], name='financas_or_ano_16571c_idx')],
            },
        ),
    ]
