# Generated by Django 5.2.11 on 2026-02-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingestao", "0003_payload_hash_unique"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dataprovenance",
            new_name="ingestao_da_fonte_c408e4_idx",
            old_name="ingestao_dat_fonte_0c7e7f_idx",
        ),
    ]
