# Generated by Django 5.2.11 on 2026-02-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pessoal", "0002_matricula_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="servidor",
            new_name="pessoal_ser_orgao_a74c3b_idx",
            old_name="pessoal_ser_orgao_2f1642_idx",
        ),
    ]
