# Generated by Django 5.2.11 on 2026-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoal', '0003_rename_pessoal_ser_orgao_2f1642_idx_pessoal_ser_orgao_a74c3b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='carga_horaria',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='servidor',
            name='cargo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servidor',
            name='funcao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
