# Generated by Django 5.2.11 on 2026-02-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fornecedores", "0002_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fornecedor",
            new_name="fornecedore_nome_a6f587_idx",
            old_name="fornecedore_nome_7698f3_idx",
        ),
        migrations.RenameIndex(
            model_name="fornecedor",
            new_name="fornecedore_cnpj_a9fb5e_idx",
            old_name="fornecedore_cnpj_3ad08c_idx",
        ),
    ]
