# Generated by Django 5.2.11 on 2026-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-valor']},
        ),
        migrations.AlterModelOptions(
            name='licitacao',
            options={'ordering': ['-valor']},
        ),
        migrations.AddField(
            model_name='contrato',
            name='ano',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fonte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='ano',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='fonte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='link_edital',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='tipo_objeto',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
